### PR TITLE
I think we should reset the counter to avoid it reaching the int32 limit

### PR DESCRIPTION
**Pull request by NathanPB**
Just in case, you never know

### CODE REVIEW

**Comment by inthmafr** [comment]
Agreed

**Comment by narze** [comment]
Nice idea, but please resolve the conflict and hope I can merge it in time.
By the way it will not start from 0->1 as you think.

**Review by narze — APPROVED** [review]

**Comment by narze** [comment]
The true reset button is everyone unstar the repo, I delete the repo, or Github banned me.

**Comment by NathanPB** [comment]
I'm sorry but the conflicts are too complex, I will need to close the PR as I'm unable to maintain the code

image

**Comment by narze** [comment]
😂

**Pull request closed without merging**
